---
environment: production
chdir: /data/mathserver
address: 0.0.0.0
user: ubuntu
group: ubuntu
port: 80
pid: /data/mathserver/tmp/thin.pid
rackup: /data/mathserver/config.ru
log: /data/mathserver/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true